### ISSUE TITLE
Empty Shulker Nest Chests

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Issues#1]
The chests that are in the Shulker Nests or abandoned houses don't appear to have any loot in them by default.

**Comment by dfsek** [comment]
The Shulker Nests I can confirm are missing loot, but not the Abandoned houses. Are both missing it, or just the Nests?

**Comment by DeathShadez** [comment]
Just the nests. Sorry about the misconception as they were described as ruined houses.

**Comment by dfsek** [comment]
This has been fixed in 1.0.1
